// =============================================================================
// Route Manifest — Single source of truth for all routes
// =============================================================================

export interface Route {
  path: string;
  title: string;
  h1: string;
  description: string;
  phase: 1 | 2 | 3 | 4 | 5;
  parent?: string;
  schemaType: string;
}

export const routes: Route[] = [
  // =========================================================================
  // Phase 1 — Core
  // =========================================================================
  {
    path: '/',
    title: 'AI SEO & Digital Growth Consultant | Kanok Miah',
    h1: 'Digital Growth & AI SEO Consultant',
    description: 'Kanok Miah — a results-driven digital marketing expert in Dhaka, Bangladesh. Specializing in SEO, Facebook Ads, Google Ads, Social Media Marketing, Content Marketing, and Web Development.',
    phase: 1,
    schemaType: 'Person',
  },
  {
    path: '/about/',
    title: 'About Kanok Miah | SEO & AI Search Consultant',
    h1: 'Kanok Miah — SEO consultant since 2019',
    description: 'Learn about Kanok Miah — a digital growth and AI SEO consultant with 6+ years of experience and 210+ SEO campaigns.',
    phase: 1,
    parent: '/',
    schemaType: 'ProfilePage',
  },
  {
    path: '/contact/',
    title: 'Contact Kanok Miah | Free Strategy Call',
    h1: 'Book a free 30-minute strategy call',
    description: 'Book a free 30-minute strategy call with Kanok Miah. Get an audit and 3 actionable steps for your business.',
    phase: 1,
    parent: '/',
    schemaType: 'ContactPage',
  },
  {
    path: '/request-a-quote/',
    title: 'Request a Quote | Kanok Miah',
    h1: 'Get a scoped proposal',
    description: 'Request a custom proposal for your digital marketing and SEO needs.',
    phase: 1,
    parent: '/',
    schemaType: 'WebPage',
  },
  {
    path: '/privacy-policy/',
    title: 'Privacy Policy | Kanok Miah',
    h1: 'Privacy Policy',
    description: 'Privacy policy for kanokmiah.com',
    phase: 1,
    parent: '/',
    schemaType: 'WebPage',
  },
  {
    path: '/terms-conditions/',
    title: 'Terms & Conditions | Kanok Miah',
    h1: 'Terms & Conditions',
    description: 'Terms and conditions for kanokmiah.com',
    phase: 1,
    parent: '/',
    schemaType: 'WebPage',
  },

  // =========================================================================
  // Phase 2 — Services Hub & Pillars
  // =========================================================================
  {
    path: '/services/',
    title: 'SEO, AI SEO & Digital Marketing Services | Kanok Miah',
    h1: 'SEO & digital growth services',
    description: 'Comprehensive SEO, AI SEO, local SEO, e-commerce SEO, and digital marketing services for businesses worldwide.',
    phase: 2,
    parent: '/',
    schemaType: 'CollectionPage',
  },
  {
    path: '/services/seo/',
    title: 'SEO Services | On-Page, Off-Page & Technical SEO',
    h1: 'SEO services that drive revenue, not just rankings',
    description: 'Professional SEO services including on-page, off-page, technical, and semantic SEO for businesses of all sizes.',
    phase: 2,
    parent: '/services/',
    schemaType: 'Service',
  },
  {
    path: '/services/ai-seo/',
    title: 'AI SEO Services | AEO + GEO Optimization',
    h1: 'AI SEO: get cited by ChatGPT, Perplexity and AI Overviews',
    description: 'AI SEO services to optimize your content for ChatGPT, Perplexity, and Google AI Overviews.',
    phase: 2,
    parent: '/services/',
    schemaType: 'Service',
  },
  {
    path: '/services/local-seo/',
    title: 'Local SEO Services | Google Maps & GBP Ranking',
    h1: 'Local SEO services',
    description: 'Local SEO services to rank your business on Google Maps and attract nearby customers.',
    phase: 2,
    parent: '/services/',
    schemaType: 'Service',
  },
  {
    path: '/services/ecommerce-seo/',
    title: 'E-commerce SEO Services | More Organic Sales',
    h1: 'E-commerce SEO services',
    description: 'E-commerce SEO services to increase organic traffic and sales for your online store.',
    phase: 2,
    parent: '/services/',
    schemaType: 'Service',
  },
  {
    path: '/services/smm-panel-seo/',
    title: 'SMM Panel SEO Services | Rank Your Panel Globally',
    h1: 'SMM panel SEO services',
    description: 'Specialized SEO services for SMM panels to rank globally and attract more customers.',
    phase: 2,
    parent: '/services/',
    schemaType: 'Service',
  },
  {
    path: '/services/industrial-seo/',
    title: 'Industrial SEO Services | B2B & Manufacturing',
    h1: 'Industrial & manufacturing SEO services',
    description: 'SEO services tailored for industrial and manufacturing businesses to generate B2B leads.',
    phase: 2,
    parent: '/services/',
    schemaType: 'Service',
  },
  {
    path: '/services/international-seo/',
    title: 'International SEO Services | Hreflang & Multi-Country',
    h1: 'International SEO services',
    description: 'International SEO services for businesses targeting multiple countries and languages.',
    phase: 2,
    parent: '/services/',
    schemaType: 'Service',
  },
  {
    path: '/services/seo-consulting/',
    title: 'SEO Consulting Services | Audits & Strategy',
    h1: 'SEO consulting & audit services',
    description: 'SEO consulting services including comprehensive audits and strategic planning.',
    phase: 2,
    parent: '/services/',
    schemaType: 'Service',
  },
  {
    path: '/services/digital-marketing/',
    title: 'Digital Marketing Services | SEO, SEM & Social',
    h1: 'Digital marketing services',
    description: 'Full-service digital marketing including SEO, SEM, social media, and content marketing.',
    phase: 2,
    parent: '/services/',
    schemaType: 'Service',
  },

  // =========================================================================
  // Phase 2 — Case Studies & Blog
  // =========================================================================
  {
    path: '/case-studies/',
    title: 'SEO & PPC Case Studies | Kanok Miah',
    h1: 'Results, with the numbers',
    description: 'Real case studies with measurable results from SEO and PPC campaigns.',
    phase: 2,
    parent: '/',
    schemaType: 'CollectionPage',
  },
  {
    path: '/blog/',
    title: 'Blog | SEO & AI Search Insights',
    h1: 'Notes on search, AI answers, and growth',
    description: 'Insights on SEO, AI search optimization, and digital growth strategies.',
    phase: 2,
    parent: '/',
    schemaType: 'Blog',
  },

  // =========================================================================
  // Phase 3 — Sub-services & Case Studies
  // =========================================================================
  {
    path: '/services/seo/on-page-seo/',
    title: 'On-Page SEO Services | Content & Structure Optimization',
    h1: 'On-page SEO services',
    description: 'On-page SEO services to optimize your content, structure, and technical elements.',
    phase: 3,
    parent: '/services/seo/',
    schemaType: 'Service',
  },
  {
    path: '/services/seo/off-page-seo/',
    title: 'Off-Page SEO & Link Building Services | Kanok Miah',
    h1: 'Off-page SEO & link building services',
    description: 'Off-page SEO and link building services to increase your domain authority.',
    phase: 3,
    parent: '/services/seo/',
    schemaType: 'Service',
  },
  {
    path: '/services/seo/off-page-seo/digital-pr/',
    title: 'Digital PR Services | Authority & Brand Mentions',
    h1: 'Digital PR services',
    description: 'Digital PR services to build authority and brand mentions across the web.',
    phase: 3,
    parent: '/services/seo/off-page-seo/',
    schemaType: 'Service',
  },
  {
    path: '/services/seo/technical-seo/',
    title: 'Technical SEO Services | Crawl, Index & Core Web Vitals',
    h1: 'Technical SEO services',
    description: 'Technical SEO services to optimize crawlability, indexation, and Core Web Vitals.',
    phase: 3,
    parent: '/services/seo/',
    schemaType: 'Service',
  },
  {
    path: '/services/seo/semantic-seo/',
    title: 'Semantic SEO Services | Topical Maps & Entity SEO',
    h1: 'Semantic SEO & topical authority building',
    description: 'Semantic SEO services to build topical authority and entity optimization.',
    phase: 3,
    parent: '/services/seo/',
    schemaType: 'Service',
  },
  {
    path: '/services/ai-seo/answer-engine-optimization/',
    title: 'AEO Services | Answer Engine Optimization',
    h1: 'Answer engine optimization (AEO) services',
    description: 'AEO services to optimize your content for AI answer engines.',
    phase: 3,
    parent: '/services/ai-seo/',
    schemaType: 'Service',
  },
  {
    path: '/services/ai-seo/generative-engine-optimization/',
    title: 'GEO Services | Generative Engine Optimization',
    h1: 'Generative engine optimization (GEO) services',
    description: 'GEO services to optimize your content for generative AI search.',
    phase: 3,
    parent: '/services/ai-seo/',
    schemaType: 'Service',
  },
  {
    path: '/services/digital-marketing/social-media-marketing/',
    title: 'Social Media Marketing Services | Facebook, Instagram & YouTube',
    h1: 'Social media marketing services',
    description: 'Social media marketing services across Facebook, Instagram, and YouTube.',
    phase: 3,
    parent: '/services/digital-marketing/',
    schemaType: 'Service',
  },
  {
    path: '/services/digital-marketing/social-media-marketing/facebook-marketing/',
    title: 'Facebook Ads & Marketing Services | Kanok Miah',
    h1: 'Facebook marketing & ads services',
    description: 'Facebook marketing and advertising services to reach your target audience.',
    phase: 3,
    parent: '/services/digital-marketing/social-media-marketing/',
    schemaType: 'Service',
  },
  {
    path: '/services/digital-marketing/social-media-marketing/instagram-marketing/',
    title: 'Instagram Marketing Services | Kanok Miah',
    h1: 'Instagram marketing services',
    description: 'Instagram marketing services to grow your brand and engagement.',
    phase: 3,
    parent: '/services/digital-marketing/social-media-marketing/',
    schemaType: 'Service',
  },
  {
    path: '/services/digital-marketing/social-media-marketing/youtube-marketing/',
    title: 'YouTube Marketing & Ads Services | Kanok Miah',
    h1: 'YouTube marketing & ads services',
    description: 'YouTube marketing and advertising services to grow your channel and reach.',
    phase: 3,
    parent: '/services/digital-marketing/social-media-marketing/',
    schemaType: 'Service',
  },
  {
    path: '/services/digital-marketing/search-engine-marketing/',
    title: 'SEM & Google Ads Services | Kanok Miah',
    h1: 'Search engine marketing (SEM) services',
    description: 'Search engine marketing and Google Ads management services.',
    phase: 3,
    parent: '/services/digital-marketing/',
    schemaType: 'Service',
  },
  {
    path: '/services/branding/',
    title: 'Branding Services | Identity & Positioning',
    h1: 'Branding services',
    description: 'Branding services to build a strong identity and positioning for your business.',
    phase: 3,
    parent: '/services/',
    schemaType: 'Service',
  },

  // =========================================================================
  // Phase 3 — Case Studies (individual)
  // =========================================================================
  {
    path: '/case-studies/locksmith-dundee/',
    title: 'Locksmith Dundee Local SEO Case Study | Kanok Miah',
    h1: 'Locksmith Dundee — Local SEO case study',
    description: 'How we achieved +320% organic traffic and #1 local map pack for Locksmith Dundee.',
    phase: 3,
    parent: '/case-studies/',
    schemaType: 'Article',
  },
  {
    path: '/case-studies/landlord-certificates/',
    title: 'Landlord Certificates B2B Lead Gen Case Study | Kanok Miah',
    h1: 'Landlord Certificates — B2B lead gen case study',
    description: 'How we achieved +245% lead growth and +1,200 ranked keywords for Landlord Certificates.',
    phase: 3,
    parent: '/case-studies/',
    schemaType: 'Article',
  },
  {
    path: '/case-studies/das-taxis/',
    title: 'Das Taxis Mobile SEO Case Study | Kanok Miah',
    h1: 'Das Taxis — Mobile SEO case study',
    description: 'How we achieved +180% mobile traffic and +410% direct bookings for Das Taxis.',
    phase: 3,
    parent: '/case-studies/',
    schemaType: 'Article',
  },
  {
    path: '/case-studies/smmsun/',
    title: 'SMMSun SaaS SEO Case Study | Kanok Miah',
    h1: 'SMMSun — SaaS SEO case study',
    description: 'How we achieved +520% organic traffic and +4,500 top-10 keywords for SMMSun.',
    phase: 3,
    parent: '/case-studies/',
    schemaType: 'Article',
  },
  {
    path: '/case-studies/smmgen/',
    title: 'SMMGen Technical SEO Case Study | Kanok Miah',
    h1: 'SMMGen — Technical SEO case study',
    description: 'How we achieved +310% crawl efficiency and +215% sign-up growth for SMMGen.',
    phase: 3,
    parent: '/case-studies/',
    schemaType: 'Article',
  },
  {
    path: '/case-studies/morethanpanel/',
    title: 'MoreThanPanel Programmatic SEO Case Study | Kanok Miah',
    h1: 'MoreThanPanel — Programmatic SEO case study',
    description: 'How we achieved +640% MRR and +8,200 total keywords for MoreThanPanel.',
    phase: 3,
    parent: '/case-studies/',
    schemaType: 'Article',
  },
  {
    path: '/case-studies/mir-cement/',
    title: 'Mir Cement Enterprise SEO Case Study | Kanok Miah',
    h1: 'Mir Cement — Enterprise SEO case study',
    description: 'How we achieved +140% brand volume and +3,400 monthly impressions for Mir Cement.',
    phase: 3,
    parent: '/case-studies/',
    schemaType: 'Article',
  },
  {
    path: '/case-studies/dhaka-apparels/',
    title: 'Dhaka Apparels B2B SEO Case Study | Kanok Miah',
    h1: 'Dhaka Apparels — International B2B case study',
    description: 'How we achieved +410% B2B inquiries and +950 global keywords for Dhaka Apparels.',
    phase: 3,
    parent: '/case-studies/',
    schemaType: 'Article',
  },
  {
    path: '/case-studies/stealth-windshield/',
    title: 'Stealth Windshield E-commerce SEO Case Study | Kanok Miah',
    h1: 'Stealth Windshield — E-commerce SEO case study',
    description: 'How we achieved +285% organic sales and +38% SERP CTR for Stealth Windshield.',
    phase: 3,
    parent: '/case-studies/',
    schemaType: 'Article',
  },
  {
    path: '/case-studies/iqra-cadet-madrasha/',
    title: 'Iqra Cadet Madrasha Facebook Ads Case Study | Kanok Miah',
    h1: 'Iqra Cadet Madrasha — Facebook Ads case study',
    description: 'How we achieved 3.5x ROAS for Iqra Cadet Madrasha.',
    phase: 3,
    parent: '/case-studies/',
    schemaType: 'Article',
  },
  {
    path: '/case-studies/dohar-malabis/',
    title: 'দোহার মালাবিস Facebook Ads Case Study | Kanok Miah',
    h1: 'দোহার মালাবিস — Facebook Ads case study',
    description: 'How we achieved +280% monthly sales and 4.2x ROAS for দোহার মালাবিস.',
    phase: 3,
    parent: '/case-studies/',
    schemaType: 'Article',
  },
  {
    path: '/case-studies/ansar-vdp-tangail/',
    title: 'Ansar VDP Tangail Facebook Ads Case Study | Kanok Miah',
    h1: 'Ansar VDP Tangail — Facebook Ads case study',
    description: 'How we achieved 120K+ reach and +450% engagement for Ansar VDP Tangail.',
    phase: 3,
    parent: '/case-studies/',
    schemaType: 'Article',
  },
  {
    path: '/case-studies/fixzoo/',
    title: 'Fixzoo Facebook Ads Case Study | Kanok Miah',
    h1: 'Fixzoo — Facebook Ads case study',
    description: 'How we achieved 5.1x retargeting ROAS and -35% cost per purchase for Fixzoo.',
    phase: 3,
    parent: '/case-studies/',
    schemaType: 'Article',
  },
  {
    path: '/case-studies/smmjobz/',
    title: 'SMMJobz Google Ads Case Study | Kanok Miah',
    h1: 'SMMJobz — Google Ads case study',
    description: 'How we achieved +340% daily sign-ups and $0.12 avg CPL for SMMJobz.',
    phase: 3,
    parent: '/case-studies/',
    schemaType: 'Article',
  },
  {
    path: '/case-studies/cloudmatrix-technologies/',
    title: 'CloudMatrix Technologies Google Ads Case Study | Kanok Miah',
    h1: 'CloudMatrix Technologies — Google Ads case study',
    description: 'How we achieved 6.4x pipeline ROI and +215% inbound B2B leads for CloudMatrix.',
    phase: 3,
    parent: '/case-studies/',
    schemaType: 'Article',
  },
  {
    path: '/case-studies/smmrx/',
    title: 'SMMRX Google Ads Case Study | Kanok Miah',
    h1: 'SMMRX — Google Ads case study',
    description: 'How we achieved 18,500+ conversions and -42% CPA for SMMRX.',
    phase: 3,
    parent: '/case-studies/',
    schemaType: 'Article',
  },

  // =========================================================================
  // Phase 4 — Locations
  // =========================================================================
  {
    path: '/locations/',
    title: 'SEO Consultant | Bangladesh, UK, USA, Canada, UAE, Australia',
    h1: 'Where I work',
    description: 'SEO and digital marketing consulting services available in Bangladesh, UK, USA, Canada, UAE, and Australia.',
    phase: 4,
    parent: '/',
    schemaType: 'CollectionPage',
  },
  {
    path: '/locations/bangladesh/',
    title: 'SEO & Digital Marketing Consultant in Bangladesh',
    h1: 'Digital marketing & SEO consultant in Bangladesh',
    description: 'Local SEO and digital marketing consulting services in Dhaka, Bangladesh.',
    phase: 4,
    parent: '/locations/',
    schemaType: 'LocalBusiness',
  },
  {
    path: '/locations/uk/',
    title: 'SEO Consultant UK | Kanok Miah',
    h1: 'SEO & digital growth consultant for UK businesses',
    description: 'SEO consulting services for UK businesses looking to grow organically.',
    phase: 4,
    parent: '/locations/',
    schemaType: 'Service',
  },
  {
    path: '/locations/usa/',
    title: 'SEO Consultant USA | Kanok Miah',
    h1: 'SEO & AI search consultant for US businesses',
    description: 'SEO and AI search consulting services for US businesses.',
    phase: 4,
    parent: '/locations/',
    schemaType: 'Service',
  },
  {
    path: '/locations/canada/',
    title: 'SEO Consultant Canada | Kanok Miah',
    h1: 'SEO & digital growth consultant for Canadian businesses',
    description: 'SEO consulting services for Canadian businesses.',
    phase: 4,
    parent: '/locations/',
    schemaType: 'Service',
  },
  {
    path: '/locations/uae/',
    title: 'SEO Consultant UAE & Dubai | Kanok Miah',
    h1: 'SEO & digital growth consultant for UAE businesses',
    description: 'SEO consulting services for UAE and Dubai businesses.',
    phase: 4,
    parent: '/locations/',
    schemaType: 'Service',
  },
  {
    path: '/locations/australia/',
    title: 'SEO Consultant Australia | Kanok Miah',
    h1: 'SEO & digital growth consultant for Australian businesses',
    description: 'SEO consulting services for Australian businesses.',
    phase: 4,
    parent: '/locations/',
    schemaType: 'Service',
  },

  // =========================================================================
  // Phase 4 — Service × Country (gated)
  // =========================================================================
  {
    path: '/services/local-seo/uk/',
    title: 'Local SEO in UK | Kanok Miah',
    h1: 'Local SEO in UK',
    description: 'Local SEO services for UK businesses to rank on Google Maps.',
    phase: 4,
    parent: '/services/local-seo/',
    schemaType: 'Service',
  },
  {
    path: '/services/seo/uk/',
    title: 'SEO in UK | Kanok Miah',
    h1: 'SEO in UK',
    description: 'SEO services for UK businesses to increase organic traffic.',
    phase: 4,
    parent: '/services/seo/',
    schemaType: 'Service',
  },
  {
    path: '/services/ecommerce-seo/uk/',
    title: 'E-commerce SEO in UK | Kanok Miah',
    h1: 'E-commerce SEO in UK',
    description: 'E-commerce SEO services for UK online stores.',
    phase: 4,
    parent: '/services/ecommerce-seo/',
    schemaType: 'Service',
  },
  {
    path: '/services/industrial-seo/uk/',
    title: 'Industrial SEO in UK | Kanok Miah',
    h1: 'Industrial SEO in UK',
    description: 'Industrial and manufacturing SEO services for UK businesses.',
    phase: 4,
    parent: '/services/industrial-seo/',
    schemaType: 'Service',
  },
  {
    path: '/services/seo/bangladesh/',
    title: 'SEO in Bangladesh | Kanok Miah',
    h1: 'SEO in Bangladesh',
    description: 'SEO services for businesses in Bangladesh.',
    phase: 4,
    parent: '/services/seo/',
    schemaType: 'Service',
  },
  {
    path: '/services/local-seo/bangladesh/',
    title: 'Local SEO in Bangladesh | Kanok Miah',
    h1: 'Local SEO in Bangladesh',
    description: 'Local SEO services for businesses in Bangladesh.',
    phase: 4,
    parent: '/services/local-seo/',
    schemaType: 'Service',
  },
  {
    path: '/services/ecommerce-seo/bangladesh/',
    title: 'E-commerce SEO in Bangladesh | Kanok Miah',
    h1: 'E-commerce SEO in Bangladesh',
    description: 'E-commerce SEO services for Bangladeshi online stores.',
    phase: 4,
    parent: '/services/ecommerce-seo/',
    schemaType: 'Service',
  },
  {
    path: '/services/ai-seo/bangladesh/',
    title: 'AI SEO in Bangladesh | Kanok Miah',
    h1: 'AI SEO in Bangladesh',
    description: 'AI SEO services for businesses in Bangladesh.',
    phase: 4,
    parent: '/services/ai-seo/',
    schemaType: 'Service',
  },
  {
    path: '/services/digital-marketing/bangladesh/',
    title: 'Digital Marketing in Bangladesh | Kanok Miah',
    h1: 'Digital Marketing in Bangladesh',
    description: 'Digital marketing services for businesses in Bangladesh.',
    phase: 4,
    parent: '/services/digital-marketing/',
    schemaType: 'Service',
  },
  {
    path: '/services/local-seo/canada/',
    title: 'Local SEO in Canada | Kanok Miah',
    h1: 'Local SEO in Canada',
    description: 'Local SEO services for Canadian businesses.',
    phase: 4,
    parent: '/services/local-seo/',
    schemaType: 'Service',
  },
];

// Helper functions
export function getRoutesByPhase(phase: number): Route[] {
  return routes.filter((r) => r.phase === phase);
}

export function getRouteByPath(path: string): Route | undefined {
  return routes.find((r) => r.path === path);
}

export function getChildRoutes(parentPath: string): Route[] {
  return routes.filter((r) => r.parent === parentPath);
}
